"""Add phone to device

Revision ID: 50e71b155dcc
Revises: 
Create Date: 2026-03-21 00:33:42.162966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e71b155dcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'os_version')
    op.drop_column('devices', 'app_version')
    op.drop_column('devices', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('app_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('os_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
