"""actually add phone to device

Revision ID: 81190b3e84a4
Revises: 9ac1bf112964
Create Date: 2026-03-21 00:37:05.337528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81190b3e84a4'
down_revision: Union[str, Sequence[str], None] = '9ac1bf112964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'phone')
    # ### end Alembic commands ###
