"""fresh_initial_migration

Revision ID: c05e485aea8d
Revises: 
Create Date: 2026-04-16 23:02:07.081257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c05e485aea8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scam_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('scam_type', sa.Enum('INVESTMENT', 'LOAN', 'RECRUITMENT', 'IMPERSONATION', 'OTHER', name='scam_type'), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=True),
    sa.Column('reportCount', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_ai_vetted', sa.Boolean(), nullable=True),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phone_scam_uuid', 'scam_numbers', ['phone'], unique=False)
    op.create_index(op.f('ix_scam_numbers_id'), 'scam_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_scam_numbers_phone'), 'scam_numbers', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_type'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deviceId', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', 'WEB', 'OTHER', name='platform_type'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastActive', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_deviceId'), 'devices', ['deviceId'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('scam_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('deviceId', sa.String(), nullable=False),
    sa.Column('reportType', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deviceId'], ['devices.deviceId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scam_reports_deviceId'), 'scam_reports', ['deviceId'], unique=False)
    op.create_index(op.f('ix_scam_reports_id'), 'scam_reports', ['id'], unique=False)
    op.create_index(op.f('ix_scam_reports_phone'), 'scam_reports', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scam_reports_phone'), table_name='scam_reports')
    op.drop_index(op.f('ix_scam_reports_id'), table_name='scam_reports')
    op.drop_index(op.f('ix_scam_reports_deviceId'), table_name='scam_reports')
    op.drop_table('scam_reports')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_deviceId'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scam_numbers_phone'), table_name='scam_numbers')
    op.drop_index(op.f('ix_scam_numbers_id'), table_name='scam_numbers')
    op.drop_index('idx_phone_scam_uuid', table_name='scam_numbers')
    op.drop_table('scam_numbers')
    # ### end Alembic commands ###
